### ISSUE TITLE
Not working. The chat sidebar keeps loading. But when I close all (include Riot Client), it works again. So you can ignore this issue.

### ISSUE THREAD

**Issue by vonguyenminhtu2504** [molenzwiebel/Deceive#191]
---------------------------
Deceive v1.12.1
---------------------------
Deceive encountered an error and couldn't properly initialize itself. Please contact the creator through GitHub (https://github.com/molenzwiebel/Deceive) or Discord.

System.Net.Sockets.SocketException (0x80004005): No such host is known

   at System.Net.Sockets.TcpClient..ctor(String hostname, Int32 port)

   at Deceive.StartupHandler.<StartDeceiveAsync>d__3.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Deceive.StartupHandler.<Main>d__2.MoveNext()

**Comment by molenzwiebel** [comment]
This seems to be network issues. Please reopen if you continue to experience this.
